version: "3.8"

services:
    client:
        build:
            context: ./larvis-ui
            dockerfile: Dockerfile
        volumes:
            - ".:/app"
        ports:
            - "8080:80"
    server:
        build:
            context: ./larvis-server
            dockerfile: Dockerfile
        ports:
            - "8000:8080"
